services:
  tribunales_db:
    image: postgres:17
    restart: always
    container_name: tribunales_db
    environment:
      POSTGRES_USER: harvey
      POSTGRES_PASSWORD: specter
      POSTGRES_DB: sistema_tribunal
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - abogados_asociados

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: harvey@specter.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8080

    depends_on:
      - tribunales_db

    ports:
      - "8082:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - abogados_asociados

  tribunales_back:
    build: ./backend
    container_name: tribunales_back
    ports:
      - "3001:3001"
    depends_on:
      - tribunales_db
    environment:
      - DB_USER=juez_admin
      - DB_PASSWORD=tribunal_password
      - DB_NAME=sistema_tribunal
      - DB_HOST=tribunales_db
      - DB_PORT=5432
    networks:
      - abogados_asociados

  tribunales_front:
    build: ./frontend
    container_name: tribunales_front
    ports:
      - "8081:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
    networks:
      - abogados_asociados

networks:
  abogados_asociados:
    external: true
