services:
  buffect_backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - abogados_asociados
    environment:
      - TRIBUNAL_URL=http://tribunales_back:3001

  buffect_front:
    build: ./frontend
    ports:
      - "8080:5173"
    networks:
      - abogados_asociados
    depends_on:
      - buffect_backend
    environment:
      - VITE_API_URL=http://localhost:3000

networks:
  abogados_asociados:
    external: true
