services:
  buffect_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/home/app
      - /home/app/node_modules
    networks:
      - abogados_asociados
    environment:
      - TRIBUNAL_URL=http://tribunales_back:3001

  buffect_front:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - buffect_backend
    networks:
      - abogados_asociados

networks:
  abogados_asociados:
    external: true
